In [1]:
import pandas as pd

In [2]:
close_prices = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/Bitcoin_data.csv",
                           index_col=0,
                           parse_dates=True)
close_prices.head()

                       close
date
2018-05-15 06:00:00  8740.99
2018-05-15 07:00:00  8739.00
2018-05-15 08:00:00  8728.49
2018-05-15 09:00:00  8708.32
2018-05-15 10:00:00  8795.90

In [3]:
sentiment_scores = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/bitcoin_scores.csv",
                               index_col=0,
                               parse_dates=True)
sentiment_scores.head()

                     sentiment_score
date
2011-06-22 11:00:00             -1.0
2012-02-01 19:00:00              0.0
2012-03-22 20:00:00              1.0
2012-08-23 00:00:00              0.0
2012-09-07 14:00:00              0.0

In [4]:
sentiment_scores.tail()

                     sentiment_score
date
2024-01-24 13:00:00         0.000000
2024-01-24 14:00:00         0.666667
2024-01-24 15:00:00        -1.000000
2024-01-24 21:00:00         1.000000
2024-01-24 22:00:00         1.000000

In [5]:
df = pd.merge(close_prices, sentiment_scores, on='date', how='outer')

# Select dates between 2018-05-15 07:00:00 and 2024-01-24 22:00:00
df = df.loc['2018-05-15 07:00:00':'2024-01-24 22:00:00']

df.fillna(method='ffill', inplace=True)

/var/folders/xk/dxq4c_sd0_v6m2brxq2gyy7r0000gn/T/ipykernel_7818/3092810718.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [6]:
df.head()

                       close  sentiment_score
date
2018-05-15 07:00:00  8739.00              0.5
2018-05-15 08:00:00  8728.49              1.0
2018-05-15 09:00:00  8708.32              1.0
2018-05-15 10:00:00  8795.90              0.0
2018-05-15 11:00:00  8760.00              0.0

In [7]:
df.tail()

                       close  sentiment_score
date
2024-01-24 18:00:00  39754.0             -1.0
2024-01-24 19:00:00  39799.0             -1.0
2024-01-24 20:00:00  39506.0             -1.0
2024-01-24 21:00:00  39765.0              1.0
2024-01-24 22:00:00  39869.0              1.0

In [8]:
df.to_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/Bitcoin_data_full.csv")