In [1]:
# !pip3 install torch torchvision torchaudio

In [6]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

from sklearn.model_selection import train_test_split

In [3]:
data = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/Bitcoin_data.csv", 
                   index_col=0, 
                   parse_dates=True) # set index to datetime 
data.head()

                        open     high      low    close
date
2018-05-15 06:00:00  8733.86  8796.68  8707.28  8740.99
2018-05-15 07:00:00  8740.99  8766.00  8721.11  8739.00
2018-05-15 08:00:00  8739.00  8750.27  8660.53  8728.49
2018-05-15 09:00:00  8728.49  8754.40  8701.35  8708.32
2018-05-15 10:00:00  8708.32  8865.00  8695.11  8795.90

In [4]:
data = data.drop(columns=['open', 'high', 'low'])

In [5]:
data.head()

                       close
date
2018-05-15 06:00:00  8740.99
2018-05-15 07:00:00  8739.00
2018-05-15 08:00:00  8728.49
2018-05-15 09:00:00  8708.32
2018-05-15 10:00:00  8795.90

### Split data into test, val, train sets

In [ ]:
def train_test_split(data, )