In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import re

In [ ]:
df = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/RAW_bitcoin_tweets.csv", encoding="latin1")

/var/folders/xk/dxq4c_sd0_v6m2brxq2gyy7r0000gn/T/ipykernel_9771/406433593.py:1: DtypeWarning: Columns (0,5,6,7,8,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/bitcoin_tweets.csv", encoding="latin1")

In [3]:
df = df[["date", "text", "Polarity Score", "sentiment"]]

In [4]:
df = df.sort_values(by="date")

In [5]:
df = df.dropna()

In [6]:
# Try converting 'date' column to datetime, setting errors='coerce' to turn invalid dates into NaT
df["date"] = pd.to_datetime(df["date"], errors="coerce")

# Drop rows where 'date' is NaT (Not a Timestamp)
df = df.dropna(subset=["date"])

In [7]:
# Round up to the next minute 
df['date'] = df['date'].dt.ceil('min')

In [8]:
# Set 'date' column as index
df = df.set_index("date")

In [9]:
# Sort index if needed
df = df.sort_index()

In [10]:
df.head()

,text,Polarity Score,sentiment
date,,,
2021-02-05 10:53:00,2â£ Debunking 9 #Bitcoin Myths by @Patrick_...,0.0,0.0
2021-02-05 10:53:00,ð Weekend Read ð\n\nKeen to learn about...,0.0,0.0
2021-02-05 10:53:00,4â£ ðï¸ Bloomberg LP #CryptoOutlook 2021...,0.0,0.0
2021-02-05 10:53:00,"5â£ #Blockchain 50 2021 by @DelRayMan, @For...",0.0,0.0
2021-02-05 10:53:00,#reddcoin #rdd @reddcoin to the moon #altcoin ...,0.0,0.0

In [11]:
# Create a function to clean the tweets
def cleanTwt(twt):
    twt = re.sub('#bitcoin', 'bitcoin', twt) # Removing the '#'
    twt = re.sub('#Bitcoin', 'Bitcoin', twt) # Removing the '#' 
    twt = re.sub('#[A-Za-z0-9]+', '', twt) # Removing any strings with a '#' 
    twt = re.sub('https?:\/\/\S+', '', twt) # Removing URLs
    twt = re.sub('\\n', '', twt) # Removing '\n' string 
    twt = re.sub('RT[\s]+', '', twt) # Removing 'RT' string
    twt = re.sub('@[A-Za-z0-9]+', '', twt) # Removing '@' string
    twt = re.sub('[^A-Za-z0-9]+', ' ', twt) # Removing special characters
    twt = re.sub(' +', ' ', twt) # Removing extra spaces
    twt = twt.lower() # Converting to lowercase
    return twt

In [12]:
# Clean the tweets
df["text"] = df["text"].apply(cleanTwt)

In [13]:
# Drop columns
df = df.drop(columns=["Polarity Score", "sentiment"])
df.head()

                                                                  text
date
2021-02-05 10:53:00      2 debunking 9 bitcoin myths by lowry bitcoin
2021-02-05 10:53:00   weekend read keen to learn about assets check...
2021-02-05 10:53:00                  4 bloomberg lp 2021 with bitcoin
2021-02-05 10:53:00                              5 50 2021 by bitcoin
2021-02-05 10:53:00                               to the moon bitcoin

In [14]:
# Save the cleaned data
df.to_csv("/Users/alexzheng/Developer/GitHub/EC331-project/data/cleaned_bitcoin_tweets.csv")

In [ ]:
def get_sentiment(score):
    if score > 0:
        return "Positive"
    elif score == 0:
        return "Neutral"
    else:
        return "Negative"
    
# Create a new column called 'Sentiment' 
df["Sentiment"] = df["Polarity Score"].apply(get_sentiment)
df = df.drop(columns=["sentiment"])

In [ ]:
sentiment_counts = df['Sentiment'].value_counts()
print(sentiment_counts)

In [ ]:
df.head(10)

In [ ]:
df['Sentiment'].value_counts().plot(kind='bar')
plt.title('Sentiment Analysis Bar Chart')
plt.xlabel('Sentiment')
plt.ylabel('Frequency');

In [ ]:
# # Filter data for dates after 2021-08-01
# df_filtered = df[df.index >= '2021-08-21']

# # Plot sentiment scores
# plt.figure(figsize=(13, 7))
# plt.plot(df_filtered.index, df_filtered['Polarity Score'])
# plt.title('Sentiment Score Time Series')
# plt.xlabel('Date')
# plt.ylabel('Sentiment Score')
# plt.show()